baseURL: 'http://timitoerner.org/'
defaultContentLanguage: en
languageCode: en
title: Home - timitoerner
theme: ["PaperMod"]

enableRobotsTXT: true
enableGitInfo: true

params:
  defaultTheme: dark

menu:
  main:
    - identifier: posts
      url: /posts/
      name: Posts
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: github
      url: 'https://github.com/timitoerner'
      weight: 3
      pre: <span data-feather='github'></span>

